"""ViBe sample-bank ROM generator.

Reads an input.bin frame file (12-byte header + raw RGB bytes), computes a
per-pixel lookahead-median over the first N frames, applies scheme-c noise
jitter via a Xorshift32 PRNG, and writes a $readmemh-format hex file suitable
for loading by ``$readmemh`` in ``motion_core_vibe.sv``.

The bank algorithm is implemented in ``py/models/motion_vibe.py`` as
``compute_lookahead_median_bank``; this script is a thin CLI wrapper so the
generator and the in-process reference share exactly one implementation.

Usage:
    python py/gen_vibe_init_rom.py \\
        --input dv/data/input.bin \\
        --output hw/ip/motion/rtl/vibe_init_bank.mem \\
        --width 320 --height 240 \\
        --k 8 --lookahead-n 0 --seed 0xDEADBEEF

Output format ($readmemh):
    One hex string per pixel, raster-scan order (row-major, top-left first).
    Each string is 2*K hex characters long, MSB-first:
        chars [0:1]     = slot[K-1]  (highest-index sample)
        chars [2*K-2:2*K-1] = slot[0]   (lowest-index sample)
    This matches the SV concatenation ``{slot[K-1], ..., slot[0]}``.

Note: K must be 8 or 20 (the only values exercised by the RTL profiles).
"""
from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# Path setup: allow running both as ``python py/gen_vibe_init_rom.py`` from
# the repo root and as a module inside the package.
# ---------------------------------------------------------------------------
_PY_DIR = Path(__file__).parent
if str(_PY_DIR) not in sys.path:
    sys.path.insert(0, str(_PY_DIR))

from models.motion_vibe import compute_lookahead_median_bank  # noqa: E402


def _read_frames(input_path: str | Path, width: int, height: int) -> list[np.ndarray]:
    """Read all frames from a binary frame file (12-byte header + raw RGB)."""
    with open(input_path, "rb") as f:
        hdr = f.read(12)
        if len(hdr) < 12:
            raise ValueError(f"{input_path}: file too short to contain header")
        w, h, total_frames = struct.unpack("<III", hdr)
        if w != width or h != height:
            raise ValueError(
                f"{input_path}: header dims {w}x{h} != requested {width}x{height}"
            )
        pixel_bytes = f.read()

    frame_size = h * w * 3
    if len(pixel_bytes) < total_frames * frame_size:
        raise ValueError(
            f"{input_path}: expected {total_frames * frame_size} pixel bytes, "
            f"got {len(pixel_bytes)}"
        )

    frames: list[np.ndarray] = []
    for i in range(total_frames):
        raw = pixel_bytes[i * frame_size : (i + 1) * frame_size]
        frames.append(np.frombuffer(raw, dtype=np.uint8).reshape(h, w, 3).copy())
    return frames


def _write_mem(
    out_path: str | Path,
    bank: np.ndarray,
    width: int,
    height: int,
    k: int,
    seed: int,
    lookahead_n: int,
) -> None:
    """Write a $readmemh-compatible hex file from the sample bank.

    Args:
        out_path:    Destination file path.
        bank:        (H, W, K) uint8 sample bank.
        width/height/k: Dimensions (for header comment and sanity check).
        seed:        PRNG seed used to generate the bank (for header comment).
        lookahead_n: Lookahead frame count used (for header comment).
    """
    assert bank.shape == (height, width, k), (
        f"bank shape {bank.shape} != ({height}, {width}, {k})"
    )
    with open(out_path, "w") as f:
        f.write("// generated by py/gen_vibe_init_rom.py\n")
        f.write(
            f"// width={width} height={height} K={k} "
            f"seed=0x{seed:08X} lookahead_n={lookahead_n}\n"
        )
        for r in range(height):
            for c in range(width):
                # MSB-first: slot[K-1] in the most-significant bytes.
                hex_str = "".join(
                    f"{bank[r, c, k - 1 - slot]:02x}" for slot in range(k)
                )
                f.write(hex_str + "\n")


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(
        description="Generate a ViBe sample-bank ROM in $readmemh format.",
    )
    ap.add_argument("--input",        required=True, help="Input binary frame file.")
    ap.add_argument("--output",       required=True, help="Output .mem file path.")
    ap.add_argument("--width",        type=int, required=True, help="Frame width in pixels.")
    ap.add_argument("--height",       type=int, required=True, help="Frame height in pixels.")
    ap.add_argument(
        "--k", type=int, choices=[8, 20], required=True,
        help="Number of ViBe sample slots (8 or 20).",
    )
    ap.add_argument(
        "--lookahead-n", type=int, required=True,
        help="Number of leading frames to use for median (0 = all frames).",
    )
    ap.add_argument(
        "--seed",
        type=lambda s: int(s, 0),
        required=True,
        help="Xorshift32 PRNG seed (e.g. 0xDEADBEEF). Must be non-zero.",
    )
    ap.add_argument(
        "--bg-init-mode", choices=["median", "imrm", "mvtw", "mam"], default="median",
        help="BG-estimate algorithm (default: median, paper-canonical).",
    )
    ap.add_argument("--bg-init-imrm-tau",    type=int, default=20)
    ap.add_argument("--bg-init-imrm-iters",  type=int, default=3)
    ap.add_argument("--bg-init-mvtw-k",      type=int, default=24)
    ap.add_argument("--bg-init-mam-delta",   type=int, default=8)
    ap.add_argument("--bg-init-mam-dilate",  type=int, default=2)
    args = ap.parse_args(argv)

    if args.seed == 0:
        ap.error("--seed must be non-zero (0 is the Xorshift32 fixed point)")

    frames = _read_frames(args.input, args.width, args.height)
    bank = compute_lookahead_median_bank(
        frames,
        k=args.k,
        lookahead_n=args.lookahead_n,
        seed=args.seed,
        bg_init_mode=args.bg_init_mode,
        bg_init_imrm_tau=args.bg_init_imrm_tau,
        bg_init_imrm_iters=args.bg_init_imrm_iters,
        bg_init_mvtw_k=args.bg_init_mvtw_k,
        bg_init_mam_delta=args.bg_init_mam_delta,
        bg_init_mam_dilate=args.bg_init_mam_dilate,
    )
    _write_mem(
        args.output, bank, args.width, args.height, args.k,
        args.seed, args.lookahead_n,
    )
    print(
        f"gen_vibe_init_rom: wrote {args.height * args.width} pixels × {args.k} slots "
        f"→ {args.output}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
