#!/usr/bin/env python3
"""Print the 33-entry sRGB encode LUT as an SV localparam block.

Single source of truth for the sRGB curve used by axis_gamma_cor.sv and
py/models/ops/gamma_cor.py. Run manually if the curve formula changes;
copy the output into hw/ip/gamma/rtl/axis_gamma_cor.sv. The
test_gamma_cor.py parity test guards against silent drift between the
two files.
"""
from __future__ import annotations

import sys


def srgb_encode(x: float) -> float:
    """IEC 61966-2-1 sRGB encode: linear [0,1] -> non-linear [0,1]."""
    if x <= 0.0031308:
        return 12.92 * x
    return 1.055 * (x ** (1.0 / 2.4)) - 0.055


def srgb_lut() -> list[int]:
    """33-entry LUT sampled at i*8 for i in 0..32 (clamped to 255 at i=32)."""
    out = []
    for i in range(33):
        x = min(i * 8, 255) / 255.0
        out.append(round(srgb_encode(x) * 255))
    return out


def emit_sv() -> str:
    lut = srgb_lut()
    rows = []
    for r in range(0, 33, 8):
        chunk = lut[r:r + 8]
        rows.append("        " + ", ".join(f"8'd{v:>3}" for v in chunk))
    body = ",\n".join(rows)
    return (
        "    // sRGB encode LUT -- 33 entries sampled at i*8 (i=0..32).\n"
        "    // Generated by py/gen_gamma_lut.py; matched in\n"
        "    // py/models/ops/gamma_cor.py. Do NOT hand-edit.\n"
        "    localparam logic [7:0] SRGB_LUT [0:32] = '{\n"
        f"{body}\n"
        "    };\n"
    )


if __name__ == "__main__":
    sys.stdout.write(emit_sv())
