// AUTO-GENERATED by py/gen_hud_font.py — do not hand-edit.
// Edit GLYPHS in py/gen_hud_font.py and re-run, then commit both files.

package axis_hud_font_pkg;

    typedef logic [5:0] glyph_idx_t;

    // Glyph slots (must match ORDER in py/gen_hud_font.py)
    localparam glyph_idx_t G_0 = 6'd0;
    localparam glyph_idx_t G_1 = 6'd1;
    localparam glyph_idx_t G_2 = 6'd2;
    localparam glyph_idx_t G_3 = 6'd3;
    localparam glyph_idx_t G_4 = 6'd4;
    localparam glyph_idx_t G_5 = 6'd5;
    localparam glyph_idx_t G_6 = 6'd6;
    localparam glyph_idx_t G_7 = 6'd7;
    localparam glyph_idx_t G_8 = 6'd8;
    localparam glyph_idx_t G_9 = 6'd9;
    localparam glyph_idx_t G_A = 6'd10;
    localparam glyph_idx_t G_B = 6'd11;
    localparam glyph_idx_t G_C = 6'd12;
    localparam glyph_idx_t G_D = 6'd13;
    localparam glyph_idx_t G_E = 6'd14;
    localparam glyph_idx_t G_F = 6'd15;
    localparam glyph_idx_t G_G = 6'd16;
    localparam glyph_idx_t G_H = 6'd17;
    localparam glyph_idx_t G_I = 6'd18;
    localparam glyph_idx_t G_J = 6'd19;
    localparam glyph_idx_t G_K = 6'd20;
    localparam glyph_idx_t G_L = 6'd21;
    localparam glyph_idx_t G_M = 6'd22;
    localparam glyph_idx_t G_N = 6'd23;
    localparam glyph_idx_t G_O = 6'd24;
    localparam glyph_idx_t G_P = 6'd25;
    localparam glyph_idx_t G_Q = 6'd26;
    localparam glyph_idx_t G_R = 6'd27;
    localparam glyph_idx_t G_S = 6'd28;
    localparam glyph_idx_t G_T = 6'd29;
    localparam glyph_idx_t G_U = 6'd30;
    localparam glyph_idx_t G_V = 6'd31;
    localparam glyph_idx_t G_W = 6'd32;
    localparam glyph_idx_t G_X = 6'd33;
    localparam glyph_idx_t G_Y = 6'd34;
    localparam glyph_idx_t G_Z = 6'd35;
    localparam glyph_idx_t G_COLON = 6'd36;
    localparam glyph_idx_t G_SPACE = 6'd37;

    localparam int N_GLYPHS = 38;
    localparam logic [7:0] FONT_ROM [N_GLYPHS][8] = '{
        '{8'h3C, 8'h66, 8'h6E, 8'h76, 8'h66, 8'h66, 8'h3C, 8'h00},  //  0 = '0'
        '{8'h18, 8'h38, 8'h18, 8'h18, 8'h18, 8'h18, 8'h7E, 8'h00},  //  1 = '1'
        '{8'h3C, 8'h66, 8'h06, 8'h0C, 8'h30, 8'h60, 8'h7E, 8'h00},  //  2 = '2'
        '{8'h3C, 8'h66, 8'h06, 8'h1C, 8'h06, 8'h66, 8'h3C, 8'h00},  //  3 = '3'
        '{8'h0C, 8'h1C, 8'h3C, 8'h6C, 8'h7E, 8'h0C, 8'h0C, 8'h00},  //  4 = '4'
        '{8'h7E, 8'h60, 8'h7C, 8'h06, 8'h06, 8'h66, 8'h3C, 8'h00},  //  5 = '5'
        '{8'h1C, 8'h30, 8'h60, 8'h7C, 8'h66, 8'h66, 8'h3C, 8'h00},  //  6 = '6'
        '{8'h7E, 8'h06, 8'h0C, 8'h18, 8'h30, 8'h30, 8'h30, 8'h00},  //  7 = '7'
        '{8'h3C, 8'h66, 8'h66, 8'h3C, 8'h66, 8'h66, 8'h3C, 8'h00},  //  8 = '8'
        '{8'h3C, 8'h66, 8'h66, 8'h3E, 8'h06, 8'h0C, 8'h38, 8'h00},  //  9 = '9'
        '{8'h18, 8'h3C, 8'h66, 8'h66, 8'h7E, 8'h66, 8'h66, 8'h00},  // 10 = 'A'
        '{8'h7C, 8'h66, 8'h66, 8'h7C, 8'h66, 8'h66, 8'h7C, 8'h00},  // 11 = 'B'
        '{8'h3C, 8'h66, 8'h60, 8'h60, 8'h60, 8'h66, 8'h3C, 8'h00},  // 12 = 'C'
        '{8'h78, 8'h6C, 8'h66, 8'h66, 8'h66, 8'h6C, 8'h78, 8'h00},  // 13 = 'D'
        '{8'h7E, 8'h60, 8'h60, 8'h78, 8'h60, 8'h60, 8'h7E, 8'h00},  // 14 = 'E'
        '{8'h7E, 8'h60, 8'h60, 8'h78, 8'h60, 8'h60, 8'h60, 8'h00},  // 15 = 'F'
        '{8'h3C, 8'h66, 8'h60, 8'h6E, 8'h66, 8'h66, 8'h3C, 8'h00},  // 16 = 'G'
        '{8'h66, 8'h66, 8'h66, 8'h7E, 8'h66, 8'h66, 8'h66, 8'h00},  // 17 = 'H'
        '{8'h3C, 8'h18, 8'h18, 8'h18, 8'h18, 8'h18, 8'h3C, 8'h00},  // 18 = 'I'
        '{8'h1E, 8'h0C, 8'h0C, 8'h0C, 8'h0C, 8'h6C, 8'h38, 8'h00},  // 19 = 'J'
        '{8'h66, 8'h6C, 8'h78, 8'h70, 8'h78, 8'h6C, 8'h66, 8'h00},  // 20 = 'K'
        '{8'h60, 8'h60, 8'h60, 8'h60, 8'h60, 8'h60, 8'h7E, 8'h00},  // 21 = 'L'
        '{8'h63, 8'h77, 8'h7F, 8'h6B, 8'h63, 8'h63, 8'h63, 8'h00},  // 22 = 'M'
        '{8'h66, 8'h76, 8'h7E, 8'h7E, 8'h6E, 8'h66, 8'h66, 8'h00},  // 23 = 'N'
        '{8'h3C, 8'h66, 8'h66, 8'h66, 8'h66, 8'h66, 8'h3C, 8'h00},  // 24 = 'O'
        '{8'h7C, 8'h66, 8'h66, 8'h7C, 8'h60, 8'h60, 8'h60, 8'h00},  // 25 = 'P'
        '{8'h3C, 8'h66, 8'h66, 8'h66, 8'h6A, 8'h6C, 8'h36, 8'h00},  // 26 = 'Q'
        '{8'h7C, 8'h66, 8'h66, 8'h7C, 8'h78, 8'h6C, 8'h66, 8'h00},  // 27 = 'R'
        '{8'h3C, 8'h66, 8'h60, 8'h3C, 8'h06, 8'h66, 8'h3C, 8'h00},  // 28 = 'S'
        '{8'h7E, 8'h18, 8'h18, 8'h18, 8'h18, 8'h18, 8'h18, 8'h00},  // 29 = 'T'
        '{8'h66, 8'h66, 8'h66, 8'h66, 8'h66, 8'h66, 8'h3C, 8'h00},  // 30 = 'U'
        '{8'h66, 8'h66, 8'h66, 8'h66, 8'h66, 8'h3C, 8'h18, 8'h00},  // 31 = 'V'
        '{8'h63, 8'h63, 8'h63, 8'h6B, 8'h7F, 8'h77, 8'h63, 8'h00},  // 32 = 'W'
        '{8'h66, 8'h66, 8'h3C, 8'h18, 8'h3C, 8'h66, 8'h66, 8'h00},  // 33 = 'X'
        '{8'h66, 8'h66, 8'h66, 8'h3C, 8'h18, 8'h18, 8'h18, 8'h00},  // 34 = 'Y'
        '{8'h7E, 8'h06, 8'h0C, 8'h18, 8'h30, 8'h60, 8'h7E, 8'h00},  // 35 = 'Z'
        '{8'h00, 8'h18, 8'h18, 8'h00, 8'h18, 8'h18, 8'h00, 8'h00},  // 36 = ':'
        '{8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00}  // 37 = 'SPACE'
    };

endpackage
