// Copyright 2026 Sebastian Prajinariu
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Unit testbench for axis_motion_detect_vibe — external-init ghost suppression.
//
// Tests:
//   T4   Drive 60 frames of ghost_box_disappear into the DUT with an
//        externally-initialised sample bank (VIBE_BG_INIT_EXTERNAL=1,
//        INIT_BANK_FILE pointing at test4_init_bank.mem).
//        Assert frame-1 mask coverage in the ghost ROI < 1%.
//
//        The init bank was generated by:
//          python hw/ip/motion/tb/gen_golden.py --test4
//        using a lookahead-median over the first 30 frames at K=8.
//
//        Ghost-suppression semantics:
//          - ghost_box_disappear places a red box in frame 0, then pure
//            black from frame 1 onward.
//          - With VIBE_BG_INIT_EXTERNAL=1, init_phase is 0, so frame-0 is
//            processed normally (comparators run against the pre-loaded bank).
//            The bank holds background (black), the red box does not match →
//            mask = 1 on frame 0 in the ROI (correct: box is genuinely new).
//            Frame 0 is therefore expected to have HIGH mask coverage — that
//            is the correct detection result, not a ghost.
//          - From frame 1 onward, the background is black again.  Since the
//            bank was initialised with background values (not the red box),
//            the background pixels match the bank → mask = 0.  There is no
//            ghost left behind.
//          - The assertion checks frame-1 ghost ROI coverage < 1% to confirm
//            that the external-init mechanism suppresses the ghost that would
//            otherwise appear when frame-0 self-init contaminates the bank.
//
// Parameters:
//   WIDTH=32, HEIGHT=16 — small frame for fast simulation (matches Test 2/3)
//   K=8                 — same as default ViBe profile
//   GAUSS_EN=0          — raw luma, no Gaussian pre-filter
//
// Conventions: drv_* intermediaries with blocking = in initial block;
// always_ff @(posedge clk) registers them to DUT inputs; mask capture at
// negedge to avoid race with DUT always_ff outputs.
//
// The .mem file path is resolved relative to dv/sim/ (the simulation working
// directory set by the Makefile).

`timescale 1ns / 1ps

module tb_axis_motion_detect_vibe_external;

    // ---- Clock / reset / DIM parameters ----
    localparam int Width     = 32;
    localparam int Height    = 16;
    localparam int K         = 8;
    localparam int NumPix    = Width * Height;   // 512
    localparam int ClkPeriod = 10;               // 100 MHz

    // Blanking margins — same as K=8 TB.
    // With W+1-delay FIFO draining during active region, 36 cycles is sufficient.
    localparam int HBlank = 4;
    localparam int VBlank = 36;

    // ---- T4 parameters ----
    localparam int T4Frames   = 60;
    localparam int T4TotalPix = T4Frames * NumPix;   // 30720

    // Ghost ROI (_gen_ghost_box_disappear at WIDTH=32, HEIGHT=16):
    //   box_w = WIDTH/4 = 8, box_h = HEIGHT/4 = 4
    //   cx = (WIDTH - box_w) / 2 = 12, cy = (HEIGHT - box_h) / 2 = 6
    localparam int GhostBoxW = Width  / 4;                    // 8
    localparam int GhostBoxH = Height / 4;                    // 4
    localparam int GhostCx   = (Width  - GhostBoxW) / 2;     // 12
    localparam int GhostCy   = (Height - GhostBoxH) / 2;     // 6
    localparam int GhostArea = GhostBoxW * GhostBoxH;         // 32

    // T4 assertion: frame-1 ghost ROI coverage must be < 1%.
    // Frame 0 correctly detects the red box as motion (high coverage, expected).
    // Frame 1: background returns; with external-init the bank already holds
    // background values → no ghost → coverage should be ~0%.
    // Threshold set at 1% to allow minor RTL rounding; Python reference is 0.0.
    localparam real T4Threshold = 0.01;  // 1%

    // File paths — relative to dv/sim/ (simulation working directory).
    localparam string InputFile  =
        "../../hw/ip/motion/tb/golden/test4_input.bin";
    localparam string InitBankFile =
        "../../hw/ip/motion/tb/golden/test4_init_bank.mem";

    // ---- Clock ----
    logic clk = 0;
    always #(ClkPeriod/2) clk = ~clk;

    // ---- Reset ----
    logic rst_n = 1'b0;

    // ---- Driver intermediaries (blocking = in initial/task; posedge-registered) ----
    logic [23:0] drv_tdata   = '0;
    logic        drv_tvalid  = 1'b0;
    logic        drv_tlast   = 1'b0;
    logic        drv_tuser   = 1'b0;

    // ---- AXI4-Stream interfaces ----
    axis_if #(.DATA_W(24), .USER_W(1)) s_axis_pix ();
    axis_if #(.DATA_W(1),  .USER_W(1)) m_axis_msk ();

    // DUT inputs — registered on posedge to avoid INITIALDLY races.
    always_ff @(posedge clk) begin
        s_axis_pix.tdata  <= drv_tdata;
        s_axis_pix.tvalid <= drv_tvalid;
        s_axis_pix.tlast  <= drv_tlast;
        s_axis_pix.tuser  <= drv_tuser;
    end

    // Downstream always-ready consumer.
    assign m_axis_msk.tready = 1'b1;

    // ---- DUT: K=8 with VIBE_BG_INIT_EXTERNAL=1 ----
    axis_motion_detect_vibe #(
        .WIDTH                 (Width),
        .HEIGHT                (Height),
        .K                     (K),
        .GAUSS_EN              (1'b0),
        .VIBE_BG_INIT_EXTERNAL (1'b1),
        .INIT_BANK_FILE        (InitBankFile)
    ) u_dut (
        .clk_i      (clk),
        .rst_n_i    (rst_n),
        .s_axis_pix (s_axis_pix),
        .m_axis_msk (m_axis_msk)
    );

    // ---- Global error counter ----
    integer num_errors = 0;

    // =========================================================================
    // T4 mask capture — concurrent negedge block.
    // Active only when t4_active == 1.
    // =========================================================================
    logic   t4_active = 1'b0;
    integer t4_beat   = 0;

    logic t4_mask_arr [T4TotalPix];

    always @(negedge clk) begin
        if (t4_active && m_axis_msk.tvalid && m_axis_msk.tready) begin
            if (t4_beat < T4TotalPix) begin
                t4_mask_arr[t4_beat] = m_axis_msk.tdata[0];
                t4_beat = t4_beat + 1;
            end
        end
    end

    // =========================================================================
    // Utility tasks
    // =========================================================================

    task automatic do_reset();
        drv_tvalid = 1'b0;
        drv_tuser  = 1'b0;
        drv_tlast  = 1'b0;
        rst_n = 1'b0;
        repeat (8) @(posedge clk);
        rst_n = 1'b1;
        repeat (2) @(posedge clk);
    endtask

    // Drive one frame from an open binary RGB file descriptor.
    task automatic drive_frame_from_file(
        input  integer fd,
        input  integer frame_idx,
        output integer ok
    );
        integer r_byte, g_byte, b_byte;
        ok = 1;
        for (int row_i = 0; row_i < Height; row_i++) begin
            for (int col_i = 0; col_i < Width; col_i++) begin
                r_byte = $fgetc(fd);
                g_byte = $fgetc(fd);
                b_byte = $fgetc(fd);
                if (r_byte == -1 || g_byte == -1 || b_byte == -1) begin
                    $display("ERROR T4: input EOF at frame=%0d row=%0d col=%0d",
                             frame_idx, row_i, col_i);
                    ok = 0;
                    return;
                end
                drv_tdata  = {r_byte[7:0], g_byte[7:0], b_byte[7:0]};
                drv_tvalid = 1'b1;
                drv_tuser  = (row_i == 0 && col_i == 0) ? 1'b1 : 1'b0;
                drv_tlast  = (col_i == Width - 1)       ? 1'b1 : 1'b0;
                @(posedge clk);
                while (!s_axis_pix.tready) @(posedge clk);
            end
            drv_tvalid = 1'b0;
            drv_tuser  = 1'b0;
            drv_tlast  = 1'b0;
            repeat (HBlank) @(posedge clk);
        end
        repeat (VBlank) @(posedge clk);
    endtask

    task automatic skip_bytes(input integer fd, input int nb);
        for (int i = 0; i < nb; i++)
            void'($fgetc(fd));
    endtask

    // =========================================================================
    // T4: External-init ghost suppression — frame-1 ghost ROI coverage < 1%
    // =========================================================================
    task automatic run_t4();
        integer fd_in, ok;
        integer roi_ones_f1;
        real    cov_f1;

        $display("==========================================================");
        $display("T4: external-init ghost suppression (K=%0d, W=%0d, H=%0d)",
                 K, Width, Height);
        $display("  Input:    %s", InputFile);
        $display("  InitBank: %s", InitBankFile);
        $display("  Assertion: frame-1 ghost ROI coverage < %.2f%%",
                 T4Threshold * 100.0);
        $display("  (frame-0 correctly has high coverage: red box detected as motion)");
        $display("==========================================================");

        do_reset();
        t4_beat   = 0;
        t4_active = 1'b1;

        fd_in = $fopen(InputFile, "rb");
        if (fd_in == 0) begin
            $display("ERROR T4: cannot open input file: %s", InputFile);
            num_errors = num_errors + 1;
            t4_active = 1'b0;
            return;
        end

        skip_bytes(fd_in, 12);  // skip 12-byte header

        ok = 1;
        for (int f = 0; f < T4Frames && ok; f++) begin
            drive_frame_from_file(fd_in, f, ok);
        end
        $fclose(fd_in);

        if (!ok) begin
            $display("ERROR T4: input file read failed — aborting T4");
            num_errors = num_errors + 1;
            t4_active = 1'b0;
            return;
        end

        repeat (VBlank) @(posedge clk);
        t4_active = 1'b0;
        repeat (4)   @(posedge clk);

        if (t4_beat !== T4TotalPix) begin
            $display("ERROR T4: collected %0d mask beats, expected %0d",
                     t4_beat, T4TotalPix);
            num_errors = num_errors + 1;
            return;
        end

        // ---- T4: frame-1 ghost ROI coverage --------------------------------
        // Frame 0 (beats 0..NumPix-1): red box is present and correctly
        //   detected as motion (high coverage expected — not a ghost).
        // Frame 1 (beats NumPix..2*NumPix-1): pure black background.
        //   With external-init the bank holds background values → no ghost.
        //   We assert coverage < 1% here.
        roi_ones_f1 = 0;
        for (int b = NumPix; b < 2 * NumPix; b++) begin
            integer row_b, col_b;
            row_b = (b - NumPix) / Width;
            col_b = (b - NumPix) % Width;
            if (row_b >= GhostCy && row_b < GhostCy + GhostBoxH &&
                col_b >= GhostCx && col_b < GhostCx + GhostBoxW) begin
                if (t4_mask_arr[b])
                    roi_ones_f1 = roi_ones_f1 + 1;
            end
        end

        cov_f1 = real'(roi_ones_f1) / real'(GhostArea);

        $display("");
        $display("T4 ghost ROI (rows %0d-%0d, cols %0d-%0d):",
                 GhostCy, GhostCy + GhostBoxH - 1,
                 GhostCx, GhostCx + GhostBoxW - 1);
        $display("  frame-1 roi_ones = %0d / %0d pixels (ghost check)",
                 roi_ones_f1, GhostArea);
        $display("  frame-1 coverage = %.6f   threshold = %.6f",
                 cov_f1, real'(T4Threshold));

        if (cov_f1 >= real'(T4Threshold)) begin
            $error("T4 FAIL: frame-1 ghost ROI coverage %.6f >= threshold %.6f",
                   cov_f1, real'(T4Threshold));
            num_errors = num_errors + 1;
        end else begin
            $display("PASS T4: frame-1 ghost ROI coverage %.6f < threshold %.6f",
                     cov_f1, real'(T4Threshold));
        end
    endtask

    // =========================================================================
    // Main
    // =========================================================================
    initial begin
        run_t4();

        $display("");
        if (num_errors > 0)
            $fatal(1, "tb_axis_motion_detect_vibe_external FAILED: %0d error(s)", num_errors);
        else begin
            $display("tb_axis_motion_detect_vibe_external PASSED — T4 OK");
            $finish;
        end
    end

    // ---- Timeout guard (5 ms is ample for 60 frames at 100 MHz) ----
    initial begin
        #5_000_000;
        $fatal(1, "tb_axis_motion_detect_vibe_external TIMEOUT after 5 ms sim time");
    end

endmodule
