// Copyright 2026 Sebastian Prajinariu
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Unit testbench for axis_motion_detect_vibe — K=20 parametrization.
//
// Tests:
//   T3   ghost_box_disappear x 200 frames — bit-exact mask compare against
//        Python ViBe reference with K=20 (hw/ip/motion/tb/golden/test3_k20_*).
//        Golden files generated by:  python gen_golden.py --k 20
//
//   T3b  Ghost ROI coverage decay — assert that K=20 diffusion has substantially
//        reduced ghost coverage in frames 150-199 vs frames 10-29.
//        Threshold pinned from Python reference (gen_golden.py --k 20):
//          avg_early  = 0.921875  (frames 10-29)
//          avg_late   = 0.045625  (frames 150-199)
//          ratio      = 0.049492
//          threshold  = 1.25 * ratio = 0.061864
//        If T3 passes (bit-exact), T3b is guaranteed to pass — it exists
//        for human readability of the coverage decay.
//
// Parameters:
//   WIDTH=32, HEIGHT=16 — small frame for fast simulation
//   K=20                — literature-default ViBe sample-set size
//   GAUSS_EN=0          — raw luma, no Gaussian pre-filter
//
// Conventions: drv_* intermediaries with blocking = in initial block;
// always_ff @(posedge clk) registers them to DUT inputs; mask capture at
// negedge to avoid race with DUT always_ff outputs.

`timescale 1ns / 1ps

module tb_axis_motion_detect_vibe_k20;

    // ---- Clock / reset / DIM parameters ----
    localparam int Width     = 32;
    localparam int Height    = 16;
    localparam int K         = 20;
    localparam int NumPix    = Width * Height;   // 512
    localparam int ClkPeriod = 10;               // 100 MHz

    // Blanking margins: VBlank must exceed worst-case FIFO drain cycles.
    // With W+1-delay FIFO draining during active region, 36 cycles is sufficient
    // (Width+4 = 32+4 = 36). Phase 2 drains deferred writes during active region,
    // not during V-blank, regardless of K value.
    localparam int HBlank = 4;
    localparam int VBlank = 36;

    // ---- T3 parameters ----
    localparam int T3Frames   = 200;
    localparam int T3TotalPix = T3Frames * NumPix;   // 102400

    // Ghost ROI (_gen_ghost_box_disappear at WIDTH=32, HEIGHT=16):
    //   box_w = WIDTH/4 = 8, box_h = HEIGHT/4 = 4
    //   cx = (WIDTH - box_w) / 2 = 12, cy = (HEIGHT - box_h) / 2 = 6
    localparam int GhostBoxW = Width  / 4;                    // 8
    localparam int GhostBoxH = Height / 4;                    // 4
    localparam int GhostCx   = (Width  - GhostBoxW) / 2;     // 12
    localparam int GhostCy   = (Height - GhostBoxH) / 2;     // 6
    localparam int GhostArea = GhostBoxW * GhostBoxH;         // 32

    // Coverage windows (0-based frame indices):
    //   Early: frames 10..29 (20 frames; ghost fully established)
    //   Late:  frames 150..199 (50 frames; ghost mostly gone via diffusion)
    localparam int EarlyStart = 10;
    localparam int EarlyEnd   = 30;    // exclusive
    localparam int LateStart  = 150;
    localparam int LateEnd    = 200;   // exclusive

    // T3b threshold pinned from gen_golden.py --k 20:
    //   measured ratio avg_late/avg_early = 0.049492
    //   threshold = 1.25 * measured_ratio = 0.061864
    localparam real T3bThreshold = 0.061864;

    // File paths — relative to dv/sim/ (simulation working directory).
    localparam string InputFile  =
        "../../hw/ip/motion/tb/golden/test3_k20_input.bin";
    localparam string GoldenFile =
        "../../hw/ip/motion/tb/golden/test3_k20_ghost_box_disappear.bin";

    // ---- Clock ----
    logic clk = 0;
    always #(ClkPeriod/2) clk = ~clk;

    // ---- Reset ----
    logic rst_n = 1'b0;

    // ---- Driver intermediaries (blocking = in initial/task; posedge-registered) ----
    logic [23:0] drv_tdata   = '0;
    logic        drv_tvalid  = 1'b0;
    logic        drv_tlast   = 1'b0;
    logic        drv_tuser   = 1'b0;

    // ---- AXI4-Stream interfaces ----
    axis_if #(.DATA_W(24), .USER_W(1)) s_axis_pix ();
    axis_if #(.DATA_W(1),  .USER_W(1)) m_axis_msk ();

    // DUT inputs — registered on posedge to avoid INITIALDLY races.
    always_ff @(posedge clk) begin
        s_axis_pix.tdata  <= drv_tdata;
        s_axis_pix.tvalid <= drv_tvalid;
        s_axis_pix.tlast  <= drv_tlast;
        s_axis_pix.tuser  <= drv_tuser;
    end

    // Downstream always-ready consumer.
    assign m_axis_msk.tready = 1'b1;

    // ---- DUT: K=20 instance ----
    axis_motion_detect_vibe #(
        .WIDTH    (Width),
        .HEIGHT   (Height),
        .K        (K),
        .GAUSS_EN (1'b0)
    ) u_dut (
        .clk_i      (clk),
        .rst_n_i    (rst_n),
        .s_axis_pix (s_axis_pix),
        .m_axis_msk (m_axis_msk)
    );

    // ---- Global error counter ----
    integer num_errors = 0;

    // =========================================================================
    // T3 mask capture — concurrent negedge block.
    // Active only when t3_active == 1.
    // =========================================================================
    logic   t3_active = 1'b0;
    integer t3_beat   = 0;

    logic t3_mask_arr [T3TotalPix];

    always @(negedge clk) begin
        if (t3_active && m_axis_msk.tvalid && m_axis_msk.tready) begin
            if (t3_beat < T3TotalPix) begin
                t3_mask_arr[t3_beat] = m_axis_msk.tdata[0];
                t3_beat = t3_beat + 1;
            end
        end
    end

    // =========================================================================
    // Utility tasks
    // =========================================================================

    task automatic do_reset();
        drv_tvalid = 1'b0;
        drv_tuser  = 1'b0;
        drv_tlast  = 1'b0;
        rst_n = 1'b0;
        repeat (8) @(posedge clk);
        rst_n = 1'b1;
        repeat (2) @(posedge clk);
    endtask

    // Drive one frame from an open file descriptor fd (binary RGB).
    task automatic drive_frame_from_file(
        input  integer fd,
        input  integer frame_idx,
        output integer ok
    );
        integer r_byte, g_byte, b_byte;
        ok = 1;
        for (int row_i = 0; row_i < Height; row_i++) begin
            for (int col_i = 0; col_i < Width; col_i++) begin
                r_byte = $fgetc(fd);
                g_byte = $fgetc(fd);
                b_byte = $fgetc(fd);
                if (r_byte == -1 || g_byte == -1 || b_byte == -1) begin
                    $display("ERROR T3: input EOF at frame=%0d row=%0d col=%0d",
                             frame_idx, row_i, col_i);
                    ok = 0;
                    return;
                end
                drv_tdata  = {r_byte[7:0], g_byte[7:0], b_byte[7:0]};
                drv_tvalid = 1'b1;
                drv_tuser  = (row_i == 0 && col_i == 0) ? 1'b1 : 1'b0;
                drv_tlast  = (col_i == Width - 1)       ? 1'b1 : 1'b0;
                @(posedge clk);
                while (!s_axis_pix.tready) @(posedge clk);
            end
            drv_tvalid = 1'b0;
            drv_tuser  = 1'b0;
            drv_tlast  = 1'b0;
            repeat (HBlank) @(posedge clk);
        end
        repeat (VBlank) @(posedge clk);
    endtask

    task automatic skip_bytes(input integer fd, input int nb);
        for (int i = 0; i < nb; i++)
            void'($fgetc(fd));
    endtask

    // =========================================================================
    // T3: bit-exact mask parity vs Python K=20 ref (200 frames)
    // T3b: ghost ROI coverage decay
    // =========================================================================
    task automatic run_t3_t3b();
        integer fd_in, fd_gold, ok;
        integer t3_fail_frame, t3_fail_pix;
        logic   t3_fail_expected, t3_fail_got;
        integer t3_fail_cnt;

        // T3b accumulators
        integer roi_ones [T3Frames];
        real    early_acc, late_acc, avg_early, avg_late, ratio;
        integer early_cnt, late_cnt;

        $display("==========================================================");
        $display("T3/T3b: ghost_box_disappear x %0d frames (K=%0d)", T3Frames, K);
        $display("  Input:  %s", InputFile);
        $display("  Golden: %s", GoldenFile);
        $display("==========================================================");

        do_reset();
        t3_beat   = 0;
        t3_active = 1'b1;

        fd_in = $fopen(InputFile, "rb");
        if (fd_in == 0) begin
            $display("ERROR T3: cannot open input file: %s", InputFile);
            num_errors = num_errors + 1;
            t3_active = 1'b0;
            return;
        end
        fd_gold = $fopen(GoldenFile, "rb");
        if (fd_gold == 0) begin
            $display("ERROR T3: cannot open golden file: %s", GoldenFile);
            $fclose(fd_in);
            num_errors = num_errors + 1;
            t3_active = 1'b0;
            return;
        end

        skip_bytes(fd_in,   12);
        skip_bytes(fd_gold, 12);

        ok = 1;
        for (int f = 0; f < T3Frames && ok; f++) begin
            drive_frame_from_file(fd_in, f, ok);
        end
        $fclose(fd_in);

        if (!ok) begin
            $display("ERROR T3: input file read failed — aborting T3");
            $fclose(fd_gold);
            num_errors = num_errors + 1;
            t3_active = 1'b0;
            return;
        end

        repeat (VBlank) @(posedge clk);
        t3_active = 1'b0;
        repeat (4)   @(posedge clk);

        // ---- T3 compare ----
        t3_fail_cnt   = 0;
        t3_fail_frame = -1;
        t3_fail_pix   = -1;

        if (t3_beat !== T3TotalPix) begin
            $display("ERROR T3: collected %0d mask beats, expected %0d",
                     t3_beat, T3TotalPix);
            num_errors = num_errors + 1;
        end else begin
            for (int b = 0; b < T3TotalPix; b++) begin
                integer golden_byte;
                logic   golden_bit;
                golden_byte = $fgetc(fd_gold);
                if (golden_byte == -1) begin
                    $display("ERROR T3: golden file too short at beat %0d", b);
                    num_errors = num_errors + 1;
                    break;
                end
                golden_bit = logic'(golden_byte & 1);
                if (t3_mask_arr[b] !== golden_bit) begin
                    if (t3_fail_cnt == 0) begin
                        t3_fail_frame    = b / NumPix;
                        t3_fail_pix      = b % NumPix;
                        t3_fail_expected = golden_bit;
                        t3_fail_got      = t3_mask_arr[b];
                        $error("T3 FAIL: frame=%0d (x,y)=(%0d,%0d) expected=%b got=%b",
                               t3_fail_frame,
                               t3_fail_pix % Width, t3_fail_pix / Width,
                               t3_fail_expected, t3_fail_got);
                    end
                    t3_fail_cnt = t3_fail_cnt + 1;
                end
            end

            if (t3_fail_cnt > 0) begin
                $display("FAIL T3: %0d mismatch(es) across %0d frames",
                         t3_fail_cnt, T3Frames);
                num_errors = num_errors + 1;
            end else begin
                $display("PASS T3: %0d frames x %0d pixels — bit-exact match (K=%0d)",
                         T3Frames, NumPix, K);
            end
        end

        $fclose(fd_gold);

        // ---- T3b: ghost ROI coverage decay ----
        for (int fi = 0; fi < T3Frames; fi++)
            roi_ones[fi] = 0;

        for (int b = 0; b < T3TotalPix; b++) begin
            integer fi, pix_in_frame, row_b, col_b;
            fi           = b / NumPix;
            pix_in_frame = b % NumPix;
            row_b        = pix_in_frame / Width;
            col_b        = pix_in_frame % Width;
            if (row_b >= GhostCy && row_b < GhostCy + GhostBoxH &&
                col_b >= GhostCx && col_b < GhostCx + GhostBoxW) begin
                if (t3_mask_arr[b])
                    roi_ones[fi] = roi_ones[fi] + 1;
            end
        end

        early_acc = 0.0;
        late_acc  = 0.0;
        early_cnt = 0;
        late_cnt  = 0;

        for (int fi = 0; fi < T3Frames; fi++) begin
            real cov;
            cov = real'(roi_ones[fi]) / real'(GhostArea);
            if (fi >= EarlyStart && fi < EarlyEnd) begin
                early_acc = early_acc + cov;
                early_cnt = early_cnt + 1;
            end
            if (fi >= LateStart && fi < LateEnd) begin
                late_acc = late_acc + cov;
                late_cnt = late_cnt + 1;
            end
        end

        avg_early = early_acc / real'(early_cnt);
        avg_late  = late_acc  / real'(late_cnt);
        ratio = (avg_early > 0.0) ? (avg_late / avg_early) : 0.0;

        $display("");
        $display("T3b coverage (ghost ROI rows %0d-%0d, cols %0d-%0d):",
                 GhostCy, GhostCy + GhostBoxH - 1,
                 GhostCx, GhostCx + GhostBoxW - 1);
        $display("  avg_early (frames %0d-%0d): %.4f",
                 EarlyStart, EarlyEnd - 1, avg_early);
        $display("  avg_late  (frames %0d-%0d): %.4f",
                 LateStart,  LateEnd  - 1, avg_late);
        $display("  ratio     = %.6f   threshold = %.6f",
                 ratio, real'(T3bThreshold));

        if (ratio > real'(T3bThreshold)) begin
            $error("T3b FAIL: late=%.4f early=%.4f ratio=%.3f > threshold=%.3f",
                   avg_late, avg_early, ratio, real'(T3bThreshold));
            num_errors = num_errors + 1;
        end else begin
            $display("PASS T3b: ratio=%.6f <= threshold=%.6f",
                     ratio, real'(T3bThreshold));
        end
    endtask

    // =========================================================================
    // Main
    // =========================================================================
    initial begin
        run_t3_t3b();

        $display("");
        if (num_errors > 0)
            $fatal(1, "tb_axis_motion_detect_vibe_k20 FAILED: %0d error(s)", num_errors);
        else begin
            $display("tb_axis_motion_detect_vibe_k20 PASSED — T3, T3b OK");
            $finish;
        end
    end

    // ---- Timeout guard (10 ms is ample for 200 frames at 100 MHz) ----
    initial begin
        #10_000_000;
        $fatal(1, "tb_axis_motion_detect_vibe_k20 TIMEOUT after 10 ms sim time");
    end

endmodule
