// Copyright 2026 Sebastian Prajinariu
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// axis_gamma_cor -- per-channel sRGB display gamma correction on a 24-bit
// RGB AXIS.
//
// 33-entry LUT (sampled at pixel = i*8 for i=0..32) addressed by p[7:3];
// linear interpolation by p[2:0] gives 8-bit fractional accuracy:
//
//     addr = p[7:3]                                            // 0..31
//     frac = p[2:0]                                            // 0..7
//     out  = (LUT[addr]*(8 - frac) + LUT[addr+1]*frac) >> 3    // 8 bits
//
// Each of R/G/B is processed independently using the same LUT.
//
// Pipeline: 1 cycle of latency. Stage A registers {addr, frac} per channel
// + {tlast, tuser, valid}. Stage B computes the three interpolations
// combinationally and drives m_axis.
//
// Backpressure: standard 1-deep skid. stage_advance = m_axis.tready ||
// !valid_q; new state is latched whenever the stage can accept (downstream
// drained or stage empty), so a "consumer accepts but no new beat upstream"
// cleanly drains valid_q to 0 instead of re-emitting the same data.
//
// enable_i = 0: zero-latency combinational passthrough; the pipeline
// registers are held with valid_q=0 and ignored. Must be held frame-stable.

module axis_gamma_cor (
    // --- Clocks and resets ---
    input  logic clk_i,
    input  logic rst_n_i,

    // --- Sideband ---
    input  logic enable_i,

    // --- AXI4-Stream input (24-bit RGB) ---
    axis_if.rx s_axis,

    // --- AXI4-Stream output (24-bit RGB) ---
    axis_if.tx m_axis
);

    // sRGB encode LUT -- 33 entries sampled at i*8 (i=0..32).
    // Generated by py/gen_gamma_lut.py; matched in
    // py/models/ops/gamma_cor.py. Do NOT hand-edit.
    localparam logic [7:0] SRGB_LUT [33] = '{
        8'd  0, 8'd 50, 8'd 71, 8'd 86, 8'd 99, 8'd110, 8'd120, 8'd129,
        8'd137, 8'd145, 8'd152, 8'd159, 8'd165, 8'd171, 8'd177, 8'd182,
        8'd188, 8'd193, 8'd198, 8'd203, 8'd208, 8'd212, 8'd216, 8'd221,
        8'd225, 8'd229, 8'd233, 8'd237, 8'd241, 8'd245, 8'd248, 8'd252,
        8'd255
    };

    // ---- Stage A: latch {addr, frac} per channel + sideband ----
    logic [4:0] addr_r_q, addr_g_q, addr_b_q;
    logic [2:0] frac_r_q, frac_g_q, frac_b_q;
    logic       valid_q;
    logic       tlast_q;
    logic       tuser_q;

    // Standard 1-deep skid: stage advances when the downstream accepts
    // (output drained) OR when the stage is empty. This cleanly handles
    // "consumer ready, no new input" (valid_q drains to 0) without
    // re-emitting stale data.
    logic stage_advance;
    assign stage_advance = m_axis.tready || !valid_q;

    always_ff @(posedge clk_i) begin
        if (!rst_n_i) begin
            valid_q <= 1'b0;
            tlast_q <= 1'b0;
            tuser_q <= 1'b0;
        end else if (stage_advance) begin
            valid_q  <= s_axis.tvalid;
            tlast_q  <= s_axis.tlast;
            tuser_q  <= s_axis.tuser;
            addr_r_q <= s_axis.tdata[23:19];
            frac_r_q <= s_axis.tdata[18:16];
            addr_g_q <= s_axis.tdata[15:11];
            frac_g_q <= s_axis.tdata[10:8];
            addr_b_q <= s_axis.tdata[7:3];
            frac_b_q <= s_axis.tdata[2:0];
        end
    end

    // ---- Stage B: combinational interpolation ----
    function automatic logic [7:0] interp(input logic [4:0] addr,
                                          input logic [2:0] frac);
        logic [5:0]  addr6;
        logic [3:0]  inv;
        /* verilator lint_off UNUSEDSIGNAL */
        // sum[2:0] are the discarded fractional bits of the >> 3.
        logic [10:0] sum;
        /* verilator lint_on UNUSEDSIGNAL */
        addr6 = {1'b0, addr};
        inv   = 4'd8 - {1'b0, frac};
        sum   = SRGB_LUT[addr6] * inv + SRGB_LUT[addr6 + 6'd1] * {1'b0, frac};
        return sum[10:3];   // >> 3
    endfunction

    logic [7:0] r_out, g_out, b_out;
    assign r_out = interp(addr_r_q, frac_r_q);
    assign g_out = interp(addr_g_q, frac_g_q);
    assign b_out = interp(addr_b_q, frac_b_q);

    // ---- enable_i bypass mux ----
    always_comb begin
        if (enable_i) begin
            s_axis.tready = stage_advance;
            m_axis.tdata  = {r_out, g_out, b_out};
            m_axis.tvalid = valid_q;
            m_axis.tlast  = tlast_q;
            m_axis.tuser  = tuser_q;
        end else begin
            s_axis.tready = m_axis.tready;
            m_axis.tdata  = s_axis.tdata;
            m_axis.tvalid = s_axis.tvalid;
            m_axis.tlast  = s_axis.tlast;
            m_axis.tuser  = s_axis.tuser;
        end
    end

endmodule
